headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Devesh B\\OneDrive\\Documents\\DEVESH\\Main project\\arges-platform\\.claude\\worktrees\\obsidian-redesign\\frontend\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\Devesh B\\OneDrive\\Documents\\DEVESH\\Main project\\arges-platform\\.claude\\worktrees\\obsidian-redesign\\frontend"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/*.glb"

[headers.values]
Content-Type = "model/gltf-binary"
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]